x-postgres-environment: &postgres-environment
  POSTGRES_DB:
  POSTGRES_HOST:
  POSTGRES_PORT:
  POSTGRES_USER:
  POSTGRES_PASSWORD:

x-django-environment: &django-environment
  DJANGO_DEBUG:

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-30-nov-2024/motion-backend-assignment/motion-project-grp2:master
    environment:
      <<:
        - *django-environment
        - *postgres-environment
    ports:
      - "8000:8000"
    command: "sh /scripts/prod.sh " # Keeps the container running
    volumes:
      - static_files:/static-files
      - media_files:/media-files

  postgres:
    image: postgres:latest
    environment:
      <<:
        - *postgres-environment
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_files:/static-files
      - media_files:/media-files
      - ./nginx:/etc/nginx/conf.d/

volumes:
  postgres_data:
  static_files:
  media_files: